String.toLocaleString({

  "en": {
    "%game-intro"           : "Join the <strong>Potatos!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"https://potato2048.rafaelcenzano.com/\">potato2048.rafaelcenzano.com</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-POTATOES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'potato',
    '%4'                    : 'home fries',
    '%8'                    : 'potato gratin',
    '%16'                   : 'baked potato',
    '%32'                   : 'mashed potato',
    '%64'                   : 'hashbrown',
    '%128'                  : 'sweet potato fries',
    '%256'                  : 'crinkle cut fries',
    '%512'                  : 'curly fries',
    '%1024'                 : 'waffle fries',
    '%2048'                 : 'shoestring fries',
    '%4096'                 : 'potato chips',
    '%8192'                 : 'hasselback potato',
    '%p0'                   : 'potato',
    '%p4'                   : 'home fries',
    '%p8'                   : 'potato gratin',
    '%p16'                  : 'baked potato',
    '%p32'                  : 'mashed potato',
    '%p64'                  : 'hashbrown',
    '%p128'                 : 'sweet potato fries',
    '%p256'                 : 'crinkle cut fries',
    '%p512'                 : 'curly fries',
    '%p1024'                : 'waffle fries',
    '%p2048'                : 'shoestring fries',
    '%p4096'                : 'potato chips',
    '%p8192'                : 'hasselback potato'
  }

});
